version: "3.8"
services:
  backend:
    build: ./backend
    container_name: api_container
    ports:
      - '8000:8000'
    volumes:
      - /Users/mohammedajao/Desktop/intro-to-os-ta-interview/backend:/app
      - /Users/mohammedajao/Desktop/intro-to-os-ta-interview/backend/node_modules:/app/node_modules
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
